import {
  LucideActivity,
  LucideBell,
  LucideBuilding2,
  LucideCalendar,
  LucideCheck,
  LucideChevronLeft,
  LucideChevronDown,
  LucideChevronRight,
  LucideCircleCheck,
  LucideClock,
  LucideCreditCard,
  LucideDownload,
  LucideFileText,
  LucideInfo,
  LucideKeyRound,
  LucideLayers,
  LucideLayoutDashboard,
  LucideLifeBuoy,
  LucideListFilter,
  LucideMenu,
  LucideMessagesSquare,
  LucidePanelLeft,
  LucidePanelRight,
  LucideReceipt,
  LucideSearch,
  LucideSettings2,
  LucideShieldCheck,
  LucideSparkles,
  LucideTriangleAlert,
  LucideUserCog,
  LucideUsers,
  LucideX,
  provideLucideConfig,
  provideLucideIcons,
} from '@lucide/angular';

/** Maps legacy `app-hq-icon` names to Lucide registry keys. */
export const HQ_ICON_ALIASES: Record<string, string> = {
  dashboard: 'layout-dashboard',
  orgs: 'building-2',
  building: 'building-2',
  users: 'users',
  people: 'users',
  subs: 'credit-card',
  billing: 'receipt',
  plans: 'layers',
  entitlements: 'key-round',
  roles: 'user-cog',
  permissions: 'user-cog',
  usage: 'activity',
  support: 'life-buoy',
  messages: 'messages-square',
  security: 'shield-check',
  bell: 'bell',
  settings: 'settings-2',
  search: 'search',
  'panel-left': 'panel-left',
  'panel-right': 'panel-right',
  filter: 'list-filter',
  'chevron-down': 'chevron-down',
  'chevron-left': 'chevron-left',
  'chevron-right': 'chevron-right',
  x: 'x',
  check: 'check',
  'check-circle': 'circle-check',
  clock: 'clock',
  calendar: 'calendar',
  spark: 'sparkles',
  alert: 'triangle-alert',
  info: 'info',
  menu: 'menu',
  'file-pdf': 'file-text',
  'file-text': 'file-text',
  download: 'download',
  activity: 'activity',
};

export function resolveHqLucideIconName(name: string): string {
  return HQ_ICON_ALIASES[name] ?? name;
}

export const HQ_LUCIDE_PROVIDERS = [
  provideLucideConfig({
    strokeWidth: 2.25,
    size: 20,
  }),
  provideLucideIcons(
    LucideLayoutDashboard,
    LucideBuilding2,
    LucideCalendar,
    LucideUsers,
    LucideCreditCard,
    LucideReceipt,
    LucideLayers,
    LucideKeyRound,
    LucideActivity,
    LucideLifeBuoy,
    LucideShieldCheck,
    LucideUserCog,
    LucideBell,
    LucideSettings2,
    LucideSearch,
    LucideMessagesSquare,
    LucidePanelLeft,
    LucidePanelRight,
    LucideListFilter,
    LucideChevronDown,
    LucideChevronLeft,
    LucideChevronRight,
    LucideX,
    LucideCheck,
    LucideCircleCheck,
    LucideClock,
    LucideSparkles,
    LucideTriangleAlert,
    LucideInfo,
    LucideMenu,
    LucideFileText,
    LucideDownload,
  ),
];
